### ISSUE TITLE
Connection issue domyos bike 500

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#138]
Hi @cagnulein,

With the last commit I couldn't connect zwift to the bridge, zwift see power without value and erg mode, but doesn't see cadence.

![zwift](https://user-images.githubusercontent.com/16349940/105715103-7796e480-5f1d-11eb-887b-5891e0068564.JPG)

[debug-lun. janv. 25 13_30_56 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5866995/debug-lun.janv.25.13_30_56.2021.log)

**Comment by cagnulein** [comment]
<pre>
Debug:   BTLE_DBUS::connect() failed "org.freedesktop.DBus.Error.NoReply" "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
Debug: bluetooth.cpp void bluetooth::debug(QString) "lun. janv. 25 13:32:02 2021 1611577922505 domyosbike::errorUnknownErrorUnknown Error"
Debug: bluetooth.cpp void bluetooth::debug(QString) "lun. janv. 25 13:32:02 2021 1611577922506 Cannot connect to remote device."
Debug: domyosbike.cpp void domyosbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::ControllerState(UnconnectedState)
Debug: domyosbike.cpp void domyosbike::controllerStateChanged(QLowEnergyController::ControllerState) trying to connect back again...
Debug:   QLowEnergyControllerPrivateBluezDBus::connectToDevice()
</pre>

@kenands which was the last commit that were you using? i think you have to bisect it

**Comment by kenands** [comment]
I updated it this morning,
each time I update use Two lines below on console:
```
sudo rm -r qdomyos-zwift
git clone https://github.com/cagnulein/qdomyos-zwift.git
```

How I can do a bisect ?

thanks !

**Comment by cagnulein** [comment]
ok so looking to #136 you were using this commit https://github.com/cagnulein/qdomyos-zwift/commit/2b2347821623efeb3860cc709ff1a47b975630c0#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2

ok so for bisect you have to do this (info here https://git-scm.com/docs/git-bisect ):

# git bisect start
# git bisect bad
# git bisect good 2b2347821623efeb3860cc709ff1a47b975630c0

and then for every commit that it will prompts to you, you have to make it and try it on zwift. after each try you have to tell it if this commit is good or not with the command "git bisect bad" or "git bisect good"

**Comment by kenands** [comment]
ok thanks, I will try bisect this night

**Comment by cagnulein** [comment]
ok @kenands take your time, i'm not in a hurry :)

**Comment by kenands** [comment]
@cagnulein result of git bisect:
```
afc7cf9cc963e698f598e76105c16a708b1f3073 is the first bad commit
commit afc7cf9cc963e698f598e76105c16a708b1f3073
Date:   Wed Dec 30 11:29:33 2020 +0100

    added deviceUpdated event in order to catch the HRM devices
```

**Comment by cagnulein** [comment]
@kenands are you sure about that? this added just a stupid event (that i'm not using :D ). Let's make in this way. Take the last commit and go to the bluetooth.cpp and remove this line

`        connect(discoveryAgent, SIGNAL(deviceUpdated(const QBluetoothDeviceInfo&, QBluetoothDeviceInfo::Fields)),
                this, SLOT(deviceUpdated(const QBluetoothDeviceInfo&, QBluetoothDeviceInfo::Fields)));`

and make it again ;)
if it was the issue, it should work.

**Comment by kenands** [comment]
@cagnulein I'm not sure, strange thing, it's the bisect took 6 steps while you did much more commit so I don't understand how it found the exact bad commit.
Other strang thing when I did bisect, at one step, there was an error when I compiled, so I did a git bisect bad whithout able to test.

I tried with deleting this line in  bluetooth.cpp with last commit and it doesn't work, I don't forgot to make it this time lol

**Comment by cagnulein** [comment]
infact i guess you did something wrong during bisect, it's impossible that this is the baddest commit ;)
bisects try to split in 2 the commits, over and over. This is how it give you few steps to have a bad commit.
During bisect, did you have a good one? Or just bads?

**Comment by kenands** [comment]
@cagnulein Ok I understand :), yes I got a good one bisect.
I will continue this night with spliting commits in 2

**Comment by cagnulein** [comment]
@kenands do you remember which is the good one?

**Comment by kenands** [comment]
Don't remember, but there is a log file 😄 

git bisect good cebdd8120a120d10f4f4e4fadc2ff9e1aa6708fc


```
git bisect start
# bad: [aff43e083a0a134295700c12d737946eab8957c2] added version to the UI
git bisect bad aff43e083a0a134295700c12d737946eab8957c2
# good: [2b2347821623efeb3860cc709ff1a47b975630c0] trying wheel revs (NOT TESTED YET)
git bisect good 2b2347821623efeb3860cc709ff1a47b975630c0
# bad: [20dad1b0f1beca4aa9d753f9ff63c2f798c69a86] added metric class. I need to do some test about this
git bisect bad 20dad1b0f1beca4aa9d753f9ff63c2f798c69a86
# bad: [7de5bf533fcd3ca5d5e64aab279e47c35466fbdc] Merge branch 'master' of https://github.com/cagnulein/qdomyos-zwift
git bisect bad 7de5bf533fcd3ca5d5e64aab279e47c35466fbdc
# bad: [36c3f039efdd190fa65202cb6d50263e281623d5] refresh bluetooth devices added to the setting page
git bisect bad 36c3f039efdd190fa65202cb6d50263e281623d5
# bad: [d6c9e84fe9183a1a92cd0da8dbb84d0d811f76e5] heart rate belt supported! need more test of course :)
git bisect bad d6c9e84fe9183a1a92cd0da8dbb84d0d811f76e5
# bad: [afc7cf9cc963e698f598e76105c16a708b1f3073] added deviceUpdated event in order to catch the HRM devices
git bisect bad afc7cf9cc963e698f598e76105c16a708b1f3073
# good: [cebdd8120a120d10f4f4e4fadc2ff9e1aa6708fc] fixed services list on virtualbike
git bisect good cebdd8120a120d10f4f4e4fadc2ff9e1aa6708fc
# first bad commit: [afc7cf9cc963e698f598e76105c16a708b1f3073] added deviceUpdated event in order to catch the HRM devices

```

**Comment by cagnulein** [comment]
i bet that the problem starts from here https://github.com/cagnulein/qdomyos-zwift/commit/d6c9e84fe9183a1a92cd0da8dbb84d0d811f76e5

in the next days i will try to give a test on my raspberry too @kenands

**Comment by kenands** [comment]
Just for information, I don't know if it related but I need to specify the name of the bike when I run the app:
 _sudo ./qdomyos-zwift -name Domyos-Bike-1175_
Otherway, bike doesn't connect, I don't know why but bluetouth of my raspberry see an other domyos-bike (Domyos-Bike-1627), I don't know if you remember my neighberhood error it still here after my moving, so I thniking there is a ghost in my bike 🤣

**Comment by cagnulein** [comment]
yes because linux as android keeps a cache of bluetooth devices so it's normal @kenands 
maybe i can give a try this afternoon

**Comment by kenands** [comment]
@cagnulein not hurry, take your time too 😄

**Comment by kenands** [comment]
Hi @cagnulein I did few test with git checkout to a specific commit to find which is the first one.
There is a compilation error with afc7cf9 that's why git bisect say that is the first one.
![image](https://user-images.githubusercontent.com/16349940/106148185-081d3100-6179-11eb-80a4-56e19297f975.png)

I tried d6c9e84 and I have the same issue with the last commit so it's possible that's the first one but I need to try all commits betwen these two commits to find the guilty commit.

**Comment by cagnulein** [comment]
yes i'm aware of that error, infact some commits later i resolved it bonded it to the qt version.
But we are near, if only i have the time to help you T_T

**Comment by kenands** [comment]
No problem :) you already make a lot.
 I plan to find the gulty commit this night or tomorrow.

**Comment by kenands** [comment]
@cagnulein I tried 4eb1523, this one work. You are right d6c9e84 is the first one that doesn't work.

if in bluetouth.cpp I delete **&& !domyosBike**

    if(b.name().startsWith("Domyos-Bike") && !b.name().startsWith("DomyosBridge") **&& !domyosBike** && filter)

the last commit works, I don't know why **domyosBike** doesn't null before the connection, maybe heart rate service of the bike detected before ?

**Comment by cagnulein** [comment]
When you say the last commit you mean that without that condition, the
current version works?

Il ven 29 gen 2021, 02:12 yusuf20 <notifications@github.com> ha scritto:

**Comment by kenands** [comment]
Yes, indeed I mean the current version d65b428 works without this condition..

**Comment by cagnulein** [comment]
wow awesome! you did a great job man! Now i have only to understand why
it's happening :D

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 gen 2021 alle ore 08:35 yusuf20 <notifications@github.com>
ha scritto:

**Comment by kenands** [comment]
Tanks :D

**Comment by cagnulein** [comment]
@kenands i guess i fixed it! take the last commit https://github.com/cagnulein/qdomyos-zwift/commit/e597e13f8c10c2eb8edffee6c6af65885c4a249d

**Comment by cagnulein** [comment]
i understand also this why happens only to you and only on raspberry: because i guess you're the one that it's using the filter option :P

**Comment by kenands** [comment]
Haha, maybe I need to clean the bluetooth cache of my raspberry :) to avoid use filter option.
Many thanks for this commit 😄

**Comment by kenands** [comment]
It works :D

**Comment by cagnulein** [comment]
great team @kenands !
